name: Build and Release Zip Archives of Web MiniDisc ğŸ’½
on:
  push:
    tags:
      - '*'
jobs:
  create-zip-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Install system dependencies ğŸ—
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential libudev-dev libusb-1.0-0-dev

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Build no-ga Release ğŸ”§
        run: |
          npm install
          npm run build
        env:
          CI: false # Do not treat warnings as errors
          PUBLIC_URL: ./
          REACT_APP_NO_GA_RELEASE: true # disables service workers and GA

      - name: Create Archive ğŸ“¦
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'release-no-ga.zip'
          directory: 'build'
          exclusions: '.DS_Store service-worker.js final-service-worker.js extra-service-worker.js'

      - name: Copy Release Archive
        run: mv build/release-no-ga.zip ./

      - name: Build Release ğŸ”§
        run: npm run build
        env:
          CI: false # Do not treat warnings as errors
          PUBLIC_URL: ./

      - name: Create Archive ğŸ“¦
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'release.zip'
          directory: 'build'
          exclusions: '.DS_Store'

      - name: Copy no-g Release Archive
        run: mv build/release.zip ./

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release.zip,release-no-g.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          replacesArtifacts: true
